name: build

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/build.yml"

permissions:
  contents: read

env:
  GO_VERSION: '1.24.2'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: go build
        run: go build -v ./...

  build-gleam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"
      - name: Compile gleam to js
        run: |
          cd internal/server/_client
          gleam deps download
          gleam run -m lustre/dev build app
      - name: Ensure compiled files haven't changed
        run: |
          if git --no-pager diff --name-only | grep -q "priv/static"; then
            echo "compiled files have changed; compile them again"
            git --no-pager diff --name-only
            false
          fi
