name: dstlled-diff

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dstlled-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get commits
        env:
          STARTING_COMMIT: ${{ github.event.pull_request.base.sha }}
          ENDING_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "start: $STARTING_COMMIT"
          echo "end: $ENDING_COMMIT"
