name: dstlled-diff

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "**.go"

permissions:
  contents: read
  pull-requests: write

jobs:
  dstlled-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get-dstlled-diff
        uses: dhth/dstlled-diff-action@0ab616345f8816e9046fdefec81b14ada815aaca # v0.2.0
        with:
          pattern: '**.go'
          starting-commit: ${{ github.event.pull_request.base.sha }}
          ending-commit: ${{ github.event.pull_request.head.sha }}
          post-comment-on-pr: 'true'
